name 'user_ssh_test'
maintainer 'Ben Hughes'
maintainer_email 'bmhughes@bmhughes.co.uk'
license 'Apache-2.0'
description 'Installs/Configures test'
version '0.1.0'
chef_version '>= 14.0'
depends 'user_ssh'
